name: Docker build & push
on:
  push:
  release:
    types: [published]
jobs:
  build:
    env:
      REGISTRY: ghcr.io
      IMAGENAME: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: Docker build
      uses: mr-smithers-excellent/docker-build-push@v5
      id: build
      with:
        image: ${{ env.IMAGENAME }}
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout deployment repo
      uses: actions/checkout@v2
      with:
        repository: getalby/alby-deployment
        path: infrastructure
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Update prod environment
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: fjogeleit/yaml-update-action@v0.7.0
      with:
        valueFile: 'alby-mainnet-deployment/values.yaml'
        propertyPath: 'sell-lsat-files.image.tag'
        value: ${{ steps.build.outputs.tags }}
        repository: getalby/alby-deployment
        branch: main
        createPR: false
        message: 'CD: Update sell-lsat-files tag to ${{ steps.build.outputs.tags }}'
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        workDir: infrastructure